
    var data = [{
        src:"http://oy7wctc5d.bkt.clouddn.com/DSC01000.jpg",
        smallsrc:"http://oy7wbg13x.bkt.clouddn.com/DSC01000.jpg",
        type:"stamps",
        descripe:"第十六届亚洲国际邮票展览纪念封 正面",
        id:"stamp1"
    },{
        src:"http://oy7wctc5d.bkt.clouddn.com/DSC01001.jpg",
        smallsrc:"http://oy7wbg13x.bkt.clouddn.com/DSC01001.jpg",
        type:"stamps",
        descripe:"第十六届亚洲国际邮票展览纪念封 反面",
        id:"stamp2"
    },{
        src:"http://oy7wctc5d.bkt.clouddn.com/DSC01002.jpg",
        smallsrc:"http://oy7wbg13x.bkt.clouddn.com/DSC01002.jpg",
        type:"stamps",
        descripe:"中华全国集邮联合会成立二十周年纪念封 正面",
        id:"stamp3"
    },{
        src:"http://oy7wctc5d.bkt.clouddn.com/DSC01003.jpg",
        smallsrc:"http://oy7wbg13x.bkt.clouddn.com/DSC01003.jpg",
        type:"stamps",
        descripe:"中华全国集邮联合会成立二十周年纪念封 反面",
        id:"stamp4"
    },{
        src:"http://oy7wctc5d.bkt.clouddn.com/DSC01004.jpg",
        smallsrc:"http://oy7wbg13x.bkt.clouddn.com/DSC01004.jpg",
        type:"stamps",
        descripe:"革命先辈诞辰纪念",
        id:"stamp5"
    },{
        src:"http://oy7wctc5d.bkt.clouddn.com/DSC01044.jpg",
        smallsrc:"http://oy7wbg13x.bkt.clouddn.com/DSC01044.jpg",
        type:"stamps",
        descripe:"毛主席逝世一周年纪念",
        id:"stamp6"
    },{ 
        src:"http://oy7wctc5d.bkt.clouddn.com/DSC01051.jpg",
        smallsrc:"http://oy7wbg13x.bkt.clouddn.com/DSC01051.jpg",
        type:"stamps",
        descripe:"毛主席去安源",
        id:"stamp7"
    },{
        src:"http://oy7wbg13x.bkt.clouddn.com/DSC01052.jpg",
        smallsrc:"http://oy7wbg13x.bkt.clouddn.com/DSC01052.jpg",
        type:"stamps",
        descripe:"毛主席诞辰一百周年",
        id:"stamp8"
    },{
        src:"http://oy7wctc5d.bkt.clouddn.com/DSC01053.jpg",
        smallsrc:"http://oy7wbg13x.bkt.clouddn.com/DSC01053.jpg",
        type:"stamps",
        descripe:"毛主席与其妻杨开慧",
        id:"stamp9"
    },{
        src:"http://oy7wctc5d.bkt.clouddn.com/DSC01054.jpg",
        smallsrc:"http://oy7wbg13x.bkt.clouddn.com/DSC01054.jpg",
        type:"stamps",
        descripe:"叶剑英同志诞生90周年",
        id:"stamp10"
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp11",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp12",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp13",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp14",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp15",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp16",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp17",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp18",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp19",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp20",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp21",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp22",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp23",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp24",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp25",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp26",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp27",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp28",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp29",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp30",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp31",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp32",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp33",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp34",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp35",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp36",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp37",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp38",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp39",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp40",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp41",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp42",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp43",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp44",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp45",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp46",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp47",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp48",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp49",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp50",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp51",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp52",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp53",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp54",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp55",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp56",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp57",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp58",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp59",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp60",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp61",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp62",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp63",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp64",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp65",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp66",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp67",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp68",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp69",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp70",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp71",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp72",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp73",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp74",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp75",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp76",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp77",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp78",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp79",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp80",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp81",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp82",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp83",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp84",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp85",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp86",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp87",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp88",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp89",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp90",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp91",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp92",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp93",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp94",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp95",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp96",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp97",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp98",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp99",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp100",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp101",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp102",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp103",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp104",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp105",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp106",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp107",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp108",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp109",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"stamps",
        descripe:"stamp110",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:""
    },{
        src:"",
        smallsrc:"",
        type:"",
        descripe:"",
        id:"" 
    }];
